name:                haskell-three
version:             0.1.0.0
github:              "githubuser/haskell-two"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

dependencies:
- base >= 4.7 && < 5

executables:
  haskell-two-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
